apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prd-cluster-dev-env
  namespace: etherpad-app-dev
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: prd