apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: create-namespaces
spec:
  resources:
    inputs:
      - {type: image, name: image}
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc apply -f onecluster-multiple-envs/apps/etherpad-multiple-envs/namespaces.yaml