apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: etherpad-prd-deployment
spec:
  workspaces:
    - name: source  
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source  
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc apply -f onecluster-multiple-envs/apps/etherpad-multiple-envs/prd/application.yaml
          oc apply -f onecluster-multiple-envs/apps/etherpad-multiple-envs/prd/channel.yaml
          oc apply -f onecluster-multiple-envs/apps/etherpad-multiple-envs/prd/placement-rule.yaml
          oc apply -f onecluster-multiple-envs/apps/etherpad-multiple-envs/prd/subscription.yaml