apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: prd-cluster-qa-env
  namespace: etherpad-app-qa
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: prd