---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: etherpad-app
  namespace: etherpad-dev
  labels:
    app: etherpad-app
  annotations:
    apps.open-cluster-management.io/github-path: onecluster-multiple-envs/resources/etherpad
spec:
  channel: etherpad/etherpad-app-latest
  placement:
    placementRef:
      kind: PlacementRule
      name: prd-clusters

