apiVersion: tekton.dev/v1beta1
kind: Task
metadata:
  name: etherpad-dev-deployment
spec:
  workspaces:
    - name: source  
  steps:
    - name: patch
      image: quay.io/openshift/origin-cli:latest
      workingDir: /workspace/source  
      command: ["/bin/bash", "-c"]
      args:
        - |-
          oc apply -f onecluster-multiple-envs/rhacm/dev/application.yaml
          oc apply -f onecluster-multiple-envs/rhacm/dev/channel.yaml
          oc apply -f onecluster-multiple-envs/rhacm/dev/placement-rule.yaml
          oc apply -f onecluster-multiple-envs/rhacm/dev/subscription.yaml